### ISSUE TITLE
"swift-syntax will automatically update to version 509.0.1. However, automatic updates may cause compilation errors."

### ISSUE THREAD

**Issue by sjustfly** [p-x9/ObfuscateMacro#12]
"swift-syntax will automatically update to version 509.0.1. However, automatic updates may cause compilation errors."

**Comment by p-x9** [comment]
CI on macOS passed with swift-syntax 509.0.1.
It may work by deleting the cache.
(On the other hand, on Linux, there seemed to be an error.)

https://github.com/p-x9/ObfuscateMacro/actions/runs/8106670756

**Comment by p-x9** [comment]
Supported `swift-syntax` version 510.0.0 on new release.
https://github.com/p-x9/ObfuscateMacro/releases/tag/0.5.0
